server:
  port: 0

spring:
  application:
    name: delivery
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  instance:
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/