spring:
  application:
    name: collector

collector:
  kafka:
    producer-properties:
      bootstrap.servers: localhost:9092
      client.id: telemetry.collector
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schema.registry.url: http://localhost:8081
    topics:
      sensors-events: telemetry.sensors.v1
      hubs-events: telemetry.hubs.v1

grpc:
  server:
    port: 9091
