spring:
  application:
    name: collector



collector:
  kafka:
    producer-properties:
      "bootstrap.servers": localhost:29092
      "client.id": telemetry.collector
      "key.serializer": org.apache.kafka.common.serialization.StringSerializer
      "value.serializer": kafka.serializer.GeneralAvroSerializer
    topics:
      sensors-events: telemetry.sensors.v1
      hubs-events: telemetry.hubs.v1
grpc:
  client:
    collector:
      address: 'static://127.0.0.1:59091'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
  server:
    port: 59091
